# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 'Build and deploy Node.js image to Azure Web Custom Container App: ${web-app-name}'

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
    - ${branch}
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '${node-version}'
    
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        # npm run test --if-present

    - name: ACR build and push image
      run: |
        az acr build --image ${{ secrets.ACR_SERVER }}/${image-name}:${{ github.sha }} \
        --registry ${{ secrets.ACR_SERVER }} --file "Dockerfile" --target ${image-build-target} .

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2    # Must login to Azure first
      with: 
        app-name: '${web-app-name}'
        slot-name: '${slot-name}'
        publish-profile: ${{ secrets.${AZURE_WEBAPP_PUBLISH_PROFILE} }}
        images: ${{ secrets.ACR_SERVER }}/${image-name}}:${{ github.sha }}

    - name: Azure logout
      run: |
        az logout
